language: php
dist: trusty
sudo: false

matrix:
  include:
    - php: "5.4"
    - php: "5.5"
    - php: "5.6"
    - php: "7.0"
    - php: "7.1"
    - php: "7.2"
    - php: "7.3"
    - php: "7.4"

install:
  - composer install
script:
  - ./vendor/bin/phpunit tests
